#!/usr/bin/env bash
# Run the assembler the VM.
# Usage: ngasm input.asm output.bin
# To get a .hex file, just run the output through xxd, either post hoc or
# like so:
# $ ngasm input.asm /dev/stdout | xxd > output.hex

ROM=${ROM:=ngasm.hex}
MODE=${MODE:=run}

rlwrap luajit main.lua \
  "flash $ROM" \
  "file $1 0x7FF0" \
  "file $2 0x7FF8 wb" \
  "$MODE"
