#!/usr/bin/env bash
# Run the assembler in the VM.
# Usage: ngasm input.asm output.hex
# The output will be in XXD hexdump format.
# You can set the ROM environment variable to point to the compiler ROM image,
# and SRC to point to the compiler source code (useful for debugging errors in
# the compiler itself).

ROM=${ROM:=stable/ngasm.hex}
SRC=${SRC:=stable/ngasm.asm}

asm="$1"
if [[ $2 == /dev/null ]]; then
  bin="/dev/null"
  hex="/dev/null"
else
  bin="$2.bin"
  hex="$2.hex"
fi
shift 2

if [[ ! $1 ]]; then
  set -- run info
fi

set -e
echo "$ROM --source $SRC --hex $hex -o $bin"
vm/vm \
  "flash $ROM" \
  "source $SRC" \
  "file $asm 0x7FF0" \
  "file $bin 0x7FF8 wb" \
  "$@"

if [[ $bin == /dev/null ]]; then exit 0; fi

# If the output was to a normal file, check its size to see if the build
# succeeded.
xxd < $bin > $hex
size=$(wc -c < $bin)
if (( size % 2 == 1 )); then
  echo -n "Build failed: "
  tail -n2 "$hex"
  exit 1
fi
