#!/usr/bin/env bash
# List a ROM image.
# Usage: nglist program.hex [program.asm]
# If the source is provided the listing will be annotated with symbol names.

vm/vm \
  "flash $1" \
  "source ${2:-/dev/null}" \
  "list"
