#!/usr/bin/env bash
#
# Run all compiler test cases.
# Call with arguments: stable-rom stable-src next-rom next-src

LUA=${LUA:=luajit}

export LUA_PATH="vm/?.lua;;"

declare -a args=()
for suite in tests/*.lua; do
  if [[ $suite != 'testlib.lua' ]]; then
    args+=($suite)
  fi
done

$LUA "tests/testlib.lua" "$@" $(ls tests/*.lua | egrep '\.lua$' | egrep -v 'testlib.lua' | sort)
